### ISSUE TITLE
Failed to Server Render (SSR) - window is not defined

### ISSUE THREAD

**Issue by maxhastingsBLA** [airbnb/lottie-web#2610]
**Tell us about your environment** React JS, gatsby
* **Browser and Browser Version:** Chrome 92.0.4515.131
*
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**
All I did was include       
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

and

      <lottie-player
        id={iconNumber}
        src={animations.account_services[iconNumber].url}
        style={{ width: '50px', height: '50px', marginBottom: '6.5px' }}
        autoplay
      />

inside of my gatsby site

**What did you expect to happen?**

i expected to not run into an error and be able to see my page when I ran "yarn start"

**What actually happened? Please include as much _relevant_ detail as possible.**
Failed to Server Render (SSR)
Error message:
window is not defined

File:
node_modules/@lottiefiles/lottie-player/dist/lottie-player.esm.js:68:1

Stack:
ReferenceError: window is not defined
    at Module../node_modules/@lottiefiles/lottie-player/dist/lottie-player.esm.js (/Users/BallastLane/Documents/harborcapital.com/public/webpack:/harborcapital.com/node_modules/@lottiefiles/lottie-player/dist/lottie-player.esm.js:68:1)
    at __webpack_require__ (/Users/BallastLane/Documents/harborcapital.com/public/webpack:/harborcapital.com/webpack/bootstrap:9:1)
    at Module../src/components/Cards/squareCard.js (/Users/BallastLane/Documents/harborcapital.com/public/render-page.js:79644:84)
    at __webpack_require__ (/Users/BallastLane/Documents/harborcapital.com/public/webpack:/harborcapital.com/webpack/bootstrap:9:1)
    at Module../src/components/FundApiComponents/AccountServices.js (/Users/BallastLane/Documents/harborcapital.com/public/render-page.js:79795:75)
    at __webpack_require__ (/Users/BallastLane/Documents/harborcapital.com/public/webpack:/harborcapital.com/webpack/bootstrap:9:1)
    at Module../src/templates/landing/index.js (/Users/BallastLane/Documents/harborcapital.com/public/render-page.js:82234:103)
    at __webpack_require__ (/Users/BallastLane/Documents/harborcapital.com/public/webpack:/harborcapital.com/webpack/bootstrap:9:1)
    at Object../.cache/_this_is_virtual_fs_path_/$virtual/ssr-sync-requires (/Users/BallastLane/Documents/harborcapital.com/public/webpack:/harborcapital.com/.cache/_this_is_virtual_fs_path_/$virtual/ssr-sync-requires:9:63)
    at __webpack_require__ (/Users/BallastLane/Documents/harborcapital.com/public/webpack:/harborcapital.com/webpack/bootstrap:9:1)

**Please provide a download link to the After Effects file that demonstrates the problem.**
don't have it

**Comment by bodymovin** [comment]
It looks like you're doing server side rendering, where window is not defined. Doing a quick google search, this is what I found.
https://www.gatsbyjs.com/docs/debugging-html-builds/

**Comment by maxhastingsBLA** [comment]
the error is in an imported package, and someone on my team told me it's usually not a good idea to edit imported packages. I am not using window anywhere in my code, the only place it's relevant here is in here (node_modules/@lottiefiles/lottie-player/dist/lottie-player.esm.js:68:1), which is something I didn't write.

**Comment by maxhastingsBLA** [comment]
I also tried putting the lottie-player component inside the useEffect but still ran into the same issue
