### ISSUE TITLE
Cannot Change color of Stroke in Lottie but can change color of Fill

### ISSUE THREAD

**Issue by bmosheGoogle** [airbnb/lottie-web#2722]
Chrome browser
After Effects Version: 2022

I am trying to load a lottie of a simple shape with a stroke and fill. After it's loaded, I would like to change the color of the stroke of a specific shape in the lottie. In this instance I have a red square with a green stroke. I would like to change the color of the green stroke to cyan. I am using lottie.min.js and lottie_api.min.js from 5.8.1

This is the example lottie file that I'm using to do this test:
https://assets1.lottiefiles.com/packages/lf20_my76bmmq.json

Here is a code snippet of how I'm trying to access and change the stroke color through its keypath:

let lottieAnimation = lottie.loadAnimation({
  container: lottieContainer,
  renderer: 'svg',
  loop: loop,
  autoplay: false,
  path: "https://assets1.lottiefiles.com/packages/lf20_my76bmmq.json"
});

lottieAnimation.addEventListener("DOMLoaded", function() {
  var animAPI;
  animAPI = lottie_api.createAnimationApi(lottieAnimation);

  // "square,Contents,Rectangle 1,Fill 1,Color" works as expected
  var color_key_path = animAPI.getKeyPath("square,Contents,Rectangle 1,Stroke 1,Color");

  // color_key_path.getPropertyAtIndex(0).getValue() is where I see the error message.
  var colorValue = color_key_path.getPropertyAtIndex(0).getValue();

  animAPI.addValueCallback(color_key_path, function(currentValue) {
    return [0,1,1,1];
  });
}); 

I should expect the stroke color to change to an opaque cyan color. When I try to access the stroke of "Rectangle 1", I get this error message:

Uncaught TypeError: Cannot read properties of undefined (reading 'getValue')
    at Array.<anonymous> (scripts/app.js:380:60)
    at AnimationItem.triggerEvent (lottie.min.js:13:3507)
    at AnimationItem.trigger (lottie.min.js:13:225237)
    at AnimationItem.<anonymous> (lottie.min.js:13:218383)

However if I try to change the Fill color of the square with the adjacent keypath "square,Contents,Rectangle 1,Fill 1,Color", it works fine. The fill color of the square is cyan.

I'm not sure if there is a bug in the library or if I'm not supposed to access the stroke keypath the same way i'm accessing the fill keypath but I would love some guidance on how to access and change the color of the stroke in a shape object in my lottie.

Thank you!

**Comment by midoisangry** [comment]
Hey there,

Just open the shape layer Contents and change "Fill" and "Stroke" to `.yourClass` or `#yourID`. Later you can call them up with that ID.
Here you can find the entry for ID's and Classes: https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

Hope This helps ;)

**Comment by midoisangry** [comment]
Here's a Codepen with a modified version of your JSON containing Classes: https://codepen.io/midoisangry/pen/bGYxVYz

**Comment by bmosheGoogle** [comment]
Thank you for the speedy response. After trying the json you provided and switching between class and id approach. It looks like I'm running into the same issue. 

.FillClass works fine to change the color but .StrokeClass does not.

**Comment by bmosheGoogle** [comment]
I was able to successfully change the stroke color in ios using the same lottie pretty trivially using

        let keypath = AnimationKeypath(keys: ["**", ".StrokeClass", "**", "Color"])
        let colorProvider = ColorValueProvider(UIColor.blue.lottieColorValue)
        animationView!.setValueProvider(colorProvider, keypath: keypath)
        
It may be that the lottie api for javascript might have a bug for changing properties in keypaths for strokes?
