### ISSUE TITLE
Animations using javascipt module fails sometimes due random bug

### ISSUE THREAD

**Issue by Nerfer1205** [airbnb/lottie-web#2881]
**Tell us about your environment**
I'm using vanilla javascript on wordpress  importing your library this way:
import lottieWeb from "https://cdn.skypack.dev/lottie-web";

* **Browser and Browser Version:**
it happens in every browser or device sometimes.

* **After Effects Version:**
I don't have this information

**What did you do? Please explain the steps you took before you encountered the problem.**
I created a instance using a json:

animation = lottieWeb.loadAnimation({
    container: document.getElementById('anim_cont'),
    path: 'https://au.viventa.co//wp-content/themes/viventa_theme/assets/animaciones/audiotest v2.json',
    renderer: 'svg',
    loop: true,
    autoplay: true,
    name: "Viventa-audiotest",
});

sometimes the console browser show the following message:

lottie-web.js:7240 Uncaught TypeError: this.audio.pause is not a function
    at AudioElement.pause (lottie-web.js:7240:18)
    at AudioController.pause (lottie-web.js:73:28)
    at AnimationItem.pause (lottie-web.js:1709:30)
    at AnimationItem.advanceTime (lottie-web.js:1818:14)
    at resume (lottie-web.js:2154:45)
AudioElement.pause @ lottie-web.js:7240
pause @ lottie-web.js:73
AnimationItem.pause @ lottie-web.js:1709
AnimationItem.advanceTime @ lottie-web.js:1818
resume @ lottie-web.js:2154
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158
requestAnimationFrame (async)
resume @ lottie-web.js:2158

and none of the animations placed in the website will work after that, they looked paused or just won´t render

**What did you expect to happen?**
animations working

**What actually happened? Please include as much _relevant_ detail as possible.**
after opening the site many times , in some occasions this error stop all my animations from working or rendering at all but after refreshing the page, the issue just disappeared.

**Please provide a download link to the After Effects file that demonstrates the problem.**
I only was provided with .json files this is the website:  https://au.viventa.co

**Comment by Nerfer1205** [comment]
In addition the animation do not have audio included
