### ISSUE TITLE
Server-side rendering: window is not defined

### ISSUE THREAD

**Issue by stefanweck** [airbnb/lottie-web#879]
When building a server side rendering build (I'm using webpack), just having `import lottie from 'lottie-web';` in your project causes the following error to show up when you try to run the server:

```project/node_modules/lottie-web/build/player/lottie.js:12
}((window || {}), function(window) {
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (/project/node_modules/lottie-web/build/player/lottie.js:12:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.defineProperty.value (/project/dist/server.js:1:203845)
    at t (/project/dist/server.js:1:163)```

**Comment by NicolaSansom** [comment]
This is lightly related to #440 see dardub's comment, it resolved the issue for me.

**Comment by bodymovin** [comment]
this should be working now.
